Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE".

# Week2 Assignments


This assignment has three components. Each of the first three components receives one point if all the tests pass. 
The last component on Pandas may require more effort, it consists of three subtasks, each of the subtasks receives 1 point.

All the exercises are designed so that the solutions will need only one or a few lines of code.

Some concepts may be new to you and may require digging into the Python, NumPy or Pandas documentation, the links are provided.

Do not hesitate to contact instuctors and TA via #week2 channel on Slack if you get stuck. Join the channel first by clicking on Channels.

## Part A. Create a missing function (1 point)

In this exercise you need to create a function __missing_link(x)__ that is passed to another function as an argument in order to perform a calculation.

We know the final result (see the assert operator), but we do not know the intermediate calculation leading to that result.

Read about Python built-in functions __all()__ and __zip()__
https://docs.python.org/3.3/library/functions.html

and about the iterators and generators here:
https://docs.python.org/3.3/library/stdtypes.html#typeiter

In [1]:
def calculate(func, it):
    """
    Performs calculation by applying *func* to each item of iterator *it*
    Returns a generator as a result.
    """
    return (2 * func(a) for a in it)

In [4]:
list(calculate(lambda x: x**2, range (9)))

[0, 2, 8, 18, 32, 50, 72, 98, 128]

In [14]:
def missing_link(x):
    """Define a function that will be passed to calculate() as an argument"""
    return x**2
    pass

## You can check the result of the missing_link() function and of calculate() if you wish:
print(list(map(missing_link, range(5))))
# print(list(calculate(missing_link, range(5))))

[0, 1, 4, 9, 16]

In [15]:
_observed_results = calculate(missing_link, range(7))
_expected_results = [0, 2, 8, 18, 32, 50, 72]

assert all(a == b for a, b in zip(_observed_results, _expected_results))

## Part B. NumPy (1 point)

Define __x__ as a subdivision of an interval from -4 PI to 4 PI into 32 equal parts, i.e. with a PI/4 step. Including both endpoints that should give 33 points.
Using NumPy calculate __cos()__ and __sin()__ and find the values of __x__ where __cos(x)__ is equal to __sin(x)__ and store these values in the variable __y__. Use NumPy vector operations.

Use __np.pi__ constant and __np.linspace()__ function: 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html

Note that due to the way floating points are stored in memory exact comparison is nearly always impossible. You should use __np.isclose()__ instead. That would allow some room for floating point errors.
https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.isclose.html

This plot may be helpful:
http://www.wolframalpha.com/input/?i=plot+sinx+and+cosx+from+-4pi+to+4pi

In [19]:
!conda list |grep numpy

numpy                     1.16.4           py37hacdab7b_0
numpy-base                1.16.4           py37h6575580_0
numpydoc                  0.9.1                      py_0

In [28]:
import numpy as np

# define x and y variables
x = np.linspace(-4*np.pi, 4*np.pi, num=33 )

y = x[np.isclose(np.cos(x), np.sin(x))]

# YOUR CODE HERE
pass

In [29]:
assert x.shape[0] == 33
assert -4*np.pi in x
assert 0.0 in x
assert 4*np.pi in x

assert y.shape[0] == 8
assert np.all(np.isclose(y/np.pi, np.array([-3.75, -2.75, -1.75, -0.75,  0.25,  1.25,  2.25,  3.25])))

## Part C. Working with Pandas dataframes (3 points)

We will explore FBI reports on gun checks provided by the National Instant Criminal Background Check System (NICS)
https://www.fbi.gov/services/cjis/nics

Before ringing up the sale, cashiers call in a check to the FBI or to other designated agencies to ensure that each customer does not have a criminal record or isnâ€™t otherwise ineligible to make a purchase. More than 230 million such checks have been made, leading to more than 1.3 million denials.

NICS and background checks is a hot topic and it is important to be able to do some basic fact-checking using the data available. https://www.washingtonpost.com/news/fact-checker/wp/2018/02/23/fact-checking-trump-nra-claims-on-gun-background-checks/?utm_term=.3e0284ad3774

The FBI NICS provides data as PDF reports, which is a really bad example of distributing the data.
There is a community-developed parser that extracted the data from PDF files. Parsed dataset that we will be using is available here: 
https://github.com/BuzzFeedNews/nics-firearm-background-checks/blob/master/README.md

Note that the number of background checks can not be directly interpreted as the number of guns sold because the actual sale protocols vary state to state.

For reproducibility we will be using a local copy of the file.

In [25]:
import pandas as pd

# NICS parsed dataset url (local copy)
url = "https://github.com/biof509/spring2019/blob/master/week2/nics-firearm-background-checks.csv?raw=true"
guns = pd.read_csv(url)

In [26]:
# Use .head() .info() and .describe() to explore the dataset

In [27]:
guns.head()

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274,0.0,12.0,...,0.0,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181,0.0,5.0,...,0.0,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693,0.0,18.0,...,1.0,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342,95.0,14.0,...,0.0,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019

In [28]:
guns.head()

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274,0.0,12.0,...,0.0,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181,0.0,5.0,...,0.0,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693,0.0,18.0,...,1.0,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342,95.0,14.0,...,0.0,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019

In [29]:
guns.shape

(13090, 27)

In [42]:
guns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13090 entries, 0 to 13089
Data columns (total 27 columns):
month                        13090 non-null object
state                        13090 non-null object
permit                       13066 non-null float64
permit_recheck               1705 non-null float64
handgun                      13070 non-null float64
long_gun                     13071 non-null float64
other                        6105 non-null float64
multiple                     13090 non-null int64
admin                        13067 non-null float64
prepawn_handgun              11147 non-null float64
prepawn_long_gun             11145 non-null float64
prepawn_other                5720 non-null float64
redemption_handgun           11150 non-null float64
redemption_long_gun          11149 non-null float64
redemption_other             5720 non-null float64
returned_handgun             2805 non-null float64
returned_long_gun            2750 non-null float64
returned_other               2420 non-null float64
rentals_handgun              1595 non-null float64
rentals_long_gun             1430 non-null float64
private_sale_handgun         3355 non-null float64
private_sale_long_gun        3355 non-null float64
private_sale_other           3355 non-null float64
return_to_seller_handgun     3080 non-null float64
return_to_seller_long_gun    3355 non-null float64
return_to_seller_other       2860 non-null float64
totals                       13090 non-null int64
dtypes: float64(23), int64(2), object(2)
memory usage: 2.7+ MB

In [43]:
guns.isna().sum()

month                            0
state                            0
permit                          24
permit_recheck               11385
handgun                         20
long_gun                        19
other                         6985
multiple                         0
admin                           23
prepawn_handgun               1943
prepawn_long_gun              1945
prepawn_other                 7370
redemption_handgun            1940
redemption_long_gun           1941
redemption_other              7370
returned_handgun             10285
returned_long_gun            10340
returned_other               10670
rentals_handgun              11495
rentals_long_gun             11660
private_sale_handgun          9735
private_sale_long_gun         9735
private_sale_other            9735
return_to_seller_handgun     10010
return_to_seller_long_gun     9735
return_to_seller_other       10230
totals                           0
dtype: int64

In [30]:
guns.loc[guns.permit.notna(), "permit":"admin" ]

         permit  permit_recheck  handgun  long_gun   other  multiple  admin
0       22465.0             0.0   5991.0    5741.0   218.0       274    0.0
1         218.0             0.0   2593.0    3057.0   220.0       181    0.0
2       12014.0           455.0  10833.0    6987.0   887.0       693    0.0
3        5684.0           690.0   4809.0    5590.0   226.0       342   95.0
4       38687.0             0.0  34617.0   25666.0  3117.0         0    0.0
5       10004.0             0.0  16160.0   12392.0  1062.0       971    0.0
6        7057.0           466.0   4519.0    1690.0   605.0         0    1.0
7         173.0             0.0   1262.0    1162.0    85.0        58    0.0
8         235.0             0.0     91.0       1.0     0.0         2    0.0
9       17524.0             0.0  44227.0   15734.0  3176.0      1935    7.0
10      17288.0             0.0  10894.0    7419.0   431.0       486    0.0
11          0.0             0.0     84.0      37.0     9.0         3    0.0
12       1125.0             0.0      0.0       0.0     0.0         0    0.0
13       5550.0             3.0   3374.0    3899.0   254.0       185    0.0
14      14583.0        199766.0  17992.0    9858.0     0.0       665    0.0
15      31327.0             0.0  15764.0   10339.0  1252.0       698   10.0
16       6819.0          5279.0    160.0    1935.0    18.0         6    0.0
17       1902.0             6.0   4500.0    4505.0   365.0       299    0.0
18     393679.0             0.0   7250.0    6241.0   306.0       490    4.0
19       2866.0            20.0   9103.0    8745.0   693.0       619    3.0
20        466.0             0.0   2835.0    2946.0   236.0       138    0.0
21          0.0             0.0      6.0       7.0     0.0         0    0.0
22       2612.0             0.0   4148.0    4001.0   103.0        34    0.0
23      10497.0             0.0   4322.0    2396.0   428.0       221    5.0
24      19265.0             6.0   8110.0    7973.0   440.0       156    0.0
25      28585.0             0.0   3773.0    8142.0   312.0       189    0.0
26       2496.0             0.0   7489.0    6695.0   320.0       394    0.0
27       1381.0             0.0  16706.0   13657.0  1371.0      1004    0.0
28       1069.0             0.0   2617.0    3805.0   162.0       218   13.0
29       2744.0            16.0     95.0    1493.0    16.0         7    0.0
...         ...             ...      ...       ...     ...       ...    ...
13060       9.0             NaN     27.0     280.0     NaN         3    0.0
13061       0.0             NaN    286.0     491.0     NaN         7    0.0
13062       0.0             NaN    116.0     458.0     NaN         4    0.0
13063       0.0             NaN    101.0      98.0     NaN         2    0.0
13064      88.0             NaN      1.0      96.0     NaN         1    0.0
13065       0.0             NaN     75.0      76.0     NaN         8    0.0
13066       0.0             NaN      8.0      46.0     NaN         1    0.0
13067       0.0             NaN     20.0      53.0     NaN         2    2.0
13068       0.0             NaN     86.0     121.0     NaN         4    0.0
13069       0.0             NaN     40.0     279.0     NaN         0    0.0
13070     524.0             NaN     87.0     695.0     NaN         4    0.0
13071       0.0             NaN     20.0      38.0     NaN         0    0.0
13072       0.0             NaN    502.0     434.0     NaN        16    0.0
13073       0.0             NaN    259.0     361.0     NaN        13    0.0
13074       0.0             NaN    153.0     186.0     NaN         5    0.0
13075       0.0             NaN      5.0       8.0     NaN         4    0.0
13076       0.0             NaN      1.0       1.0     NaN         0    0.0
13077       0.0             NaN     13.0      23.0     NaN         2    0.0
13078       0.0             NaN      0.0       6.0     NaN         0    0.0
13079       0.0             NaN      8.0      66.0     NaN         0    0.0
13080       0.0             NaN     19.0      85.0     NaN         3    0.0
13081       0.0             NaN   1384.0    1349.0     NaN        60    1.0
13082       0.0             NaN     98.0     169.0     NaN         0    0.0
13083       0.0             NaN     23.0      35.0     NaN         0    1.0
13084       0.0             NaN      0.0       0.0     NaN         0    0.0
13085       0.0             NaN     14.0       2.0     NaN         8    0.0
13086       1.0             NaN     65.0     286.0     NaN         8    1.0
13087       3.0             NaN    149.0     251.0     NaN         5    0.0
13088       0.0             NaN     25.0     214.0     NaN         2    0.0
13089       8.0             NaN     45.0      49.0     NaN         5    0.0

[13066 rows x 7 columns]

In [31]:
guns.loc[guns.permit.notna()]

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274,0.0,12.0,...,0.0,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181,0.0,5.0,...,0.0,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693,0.0,18.0,...,1.0,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342,95.0,14.0,...,0.0,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019
5,2018-08,Colorado,10004.0,0.0,16160.0,12392.0,1062.0,971,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40922
6,2018-08,Connecticut,7057.0,466.0,4519.0,1690.0,605.0,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14338
7,2018-08,Delaware,173.0,0.0,1262.0,1162.0,85.0,58,0.0,1.0,...,0.0,0.0,0.0,67.0,27.0,2.0,0.0,0.0,0.0,2914
8,2018-08,District of Columbia,235.0,0.0,91.0,1.0,0.0,2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,329
9,2018-08,Florida,17524.0,0.0,44227.0,15734.0,3176.0,1935,7.0,92.0,...,3.0,0.0,0.0,164.0,103.0,20.0,62.0,56.0,1.0,89711
10,2018-08,Georgia,17288.0,0.0,10894.0,7419.0,431.0,486,0.0,26.0,...,0.0,0.0,0.0,28.0,21.0,4.0,0.0,0.0,0.0,40046
11,2018-08,Guam,0.0,0.0,84.0,37.0,9.0,3,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,133
12,2018-08,Hawaii,1125.0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1129
13,2018-08,Idaho,5550.0,3.0,3374.0,3899.0,254.0,185,0.0,8.0,...,0.0,0.0,0.0,10.0,15.0,1.0,0.0,1.0,0.0,14312
14,2018-08,Illinois,14583.0,199766.0,17992.0,9858.0,0.0,665,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,242864
15,2018-08,Indiana,31327.0,0.0,15764.0,10339.0,1252.0,698,10.0,5.0,...,0.0,0.0,0.0,77.0,43.0,16.0,1.0,3.0,2.0,60712
16,2018-08,Iowa,6819.0,5279.0,160.0,1935.0,18.0,6,0.0,0.0,...,1.0,0.0,0.0,1.0,9.0,0.0,0.0,0.0,0.0,14306
17,2018-08,Kansas,1902.0,6.0,4500.0,4505.0,365.0,299,0.0,6.0,...,0.0,0.0,0.0,15.0,17.0,1.0,0.0,1.0,0.0,12690
18,2018-08,Kentucky,393679.0,0.0,7250.0,6241.0,306.0,490,4.0,18.0,...,0.0,0.0,0.0,30.0,45.0,1.0,0.0,1.0,0.0,411800
19,2018-08,Louisiana,2866.0,20.0,9103.0,8745.0,693.0,619,3.0,9.0,...,0.0,0.0,0.0,26.0,21.0,5.0,2.0,0.0,0.0,24273
20,2018-08,Maine,466.0,0.0,2835.0,2946.0,236.0,138,0.0,0.0,...,0.0,0.0,0.0,18.0,10.0,1.0,1.0,0.0,0.0,6951
21,2018-08,Mariana Islands,0.0,0.0,6.0,7.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13
22,2018-08,Maryland,2612.0,0.0,4148.0,4001.0,103.0,34,0.0,4.0,...,0.0,0.0,0.0,0.0,30.0,62.0,2.0,1.0,0.0,11281
23,2018-08,Massachusetts,10497.0,0.0,4322.0,2396.0,428.0,221,5.0,0.0,...,0.0,0.0,0.0,50.0,30.0,8.0,2.0,1.0,0.0,17975
24,2018-08,Michigan,19265.0,6.0,8110.0,7973.0,440.0,156,0.0,0.0,...,0.0,0.0,0.0,21.0,17.0,4.0,0.0,0.0,0.0,36381
25,2018-08,Minnesota,28585.0,0.0,3773.0,8142.0,312.0,189,0.0,1.0,...,0.0,0.0,0.0,13.0,16.0,3.0,0.0,0.0,0.0,41548
26,2018-08,Mississippi,2496.0,0.0,7489.0,6695.0,320.0,394,0.0,30.0,...,0.0,0.0,0.0,17.0,17.0,6.0,2.0,0.0,0.0,20545
27,2018-08,Missouri,1381.0,0.0,16706.0,13657.0,1371.0,1004,0.0,14.0,...,5.0,0.0,0.0,124.0,117.0,9.0,3.0,3.0,0.0,37674
28,2018-08,Montana,1069.0,0.0,2617.0,3805.0,162.0,218,13.0,5.0,...,2.0,0.0,0.0,14.0,17.0,2.0,0.0,1.0,0.0,9309
29,2018-08,Nebraska,2744.0,16.0,95.0,1493.0,16.0,7,0.0,0.0,...,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,4456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13060,1998-11,Minnesota,9.0,NaN,27.0,280.0,NaN,3,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319
13061,1998-11,Mississippi,0.0,NaN,286.0,491.0,NaN,7,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,784
13062,1998-11,Missouri,0.0,NaN,116.0,458.0,NaN,4,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,578
13063,1998-11,Montana,0.0,NaN,101.0,98.0,NaN,2,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201
13064,1998-11,Nebraska,88.0,NaN,1.0,96.0,NaN,1,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186
13065,1998-11,Nevada,0.0,NaN,75.0,76.0,NaN,8,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159
13066,1998-11,New Hampshire,0.0,NaN,8.0,46.0,NaN,1,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55
13067,1998-11,New Jersey,0.0,NaN,20.0,53.0,NaN,2,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77
13068,1998-11,New Mexico,0.0,NaN,86.0,121.0,NaN,4,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211
13069,1998-11,New York,0.0,NaN,40.0,279.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319
13070,1998-11,North Carolina,524.0,NaN,87.0,695.0,NaN,4,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1310
13071,1998-11,North Dakota,0.0,NaN,20.0,38.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58
13072,1998-11,Ohio,0.0,NaN,502.0,434.0,NaN,16,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,952
13073,1998-11,Oklahoma,0.0,NaN,259.0,361.0,NaN,13,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,633
13074,1998-11,Oregon,0.0,NaN,153.0,186.0,NaN,5,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,344
13075,1998-11,Pennsylvania,0.0,NaN,5.0,8.0,NaN,4,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13076,1998-11,Puerto Rico,0.0,NaN,1.0,1.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
13077,1998-11,Rhode Island,0.0,NaN,13.0,23.0,NaN,2,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38
13078,1998-11,South Carolina,0.0,NaN,0.0,6.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
13079,1998-11,South Dakota,0.0,NaN,8.0,66.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74
13080,1998-11,Tennessee,0.0,NaN,19.0,85.0,NaN,3,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107
13081,1998-11,Texas,0.0,NaN,1384.0,1349.0,NaN,60,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2794
13082,1998-11,Utah,0.0,NaN,98.0,169.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,267
13083,1998-11,Vermont,0.0,NaN,23.0,35.0,NaN,0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59
13084,1998-11,Virgin Islands,0.0,NaN,0.0,0.0,NaN,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
13085,1998-11,Virginia,0.0,NaN,14.0,2.0,NaN,8,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
13086,1998-11,Washington,1.0,NaN,65.0,286.0,NaN,8,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361
13087,1998-11,West Virginia,3.0,NaN,149.0,251.0,NaN,5,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,408
13088,1998-11,Wisconsin,0.0,NaN,25.0,214.0,NaN,2,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241
13089,1998-11,Wyoming,8.0,NaN,45.0,49.0,NaN,5,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107

In [32]:
guns.iloc[0,1]

'Alabama'

In [33]:
guns.notna().sum()

month                        13090
state                        13090
permit                       13066
permit_recheck                1705
handgun                      13070
long_gun                     13071
other                         6105
multiple                     13090
admin                        13067
prepawn_handgun              11147
prepawn_long_gun             11145
prepawn_other                 5720
redemption_handgun           11150
redemption_long_gun          11149
redemption_other              5720
returned_handgun              2805
returned_long_gun             2750
returned_other                2420
rentals_handgun               1595
rentals_long_gun              1430
private_sale_handgun          3355
private_sale_long_gun         3355
private_sale_other            3355
return_to_seller_handgun      3080
return_to_seller_long_gun     3355
return_to_seller_other        2860
totals                       13090
dtype: int64

In [34]:
guns.iloc[0:4, 0:3]

     month     state   permit
0  2018-08   Alabama  22465.0
1  2018-08    Alaska    218.0
2  2018-08   Arizona  12014.0
3  2018-08  Arkansas   5684.0

### Part C. Subtask 1 (1 point)

First, use __pd.to_datetime()__ with argument __yearfirst=True__ to convert the column __"month"__ to a Pandas Series with DateTime objects. Add a new column __"year"__ to __guns__ dataframe and save the results of conversion there.
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html

You can access Python __datetime.date__ objects via the __.dt__ property of Pandas Series:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.dt.date.html

Look up the attributes of __datetime.date__ class, we will need attribute __.year__
https://docs.python.org/3/library/datetime.html

In [35]:
pd.to_datetime(guns['month'], yearfirst=True).dt.year

0        2018
1        2018
2        2018
3        2018
4        2018
5        2018
6        2018
7        2018
8        2018
9        2018
10       2018
11       2018
12       2018
13       2018
14       2018
15       2018
16       2018
17       2018
18       2018
19       2018
20       2018
21       2018
22       2018
23       2018
24       2018
25       2018
26       2018
27       2018
28       2018
29       2018
         ...
13060    1998
13061    1998
13062    1998
13063    1998
13064    1998
13065    1998
13066    1998
13067    1998
13068    1998
13069    1998
13070    1998
13071    1998
13072    1998
13073    1998
13074    1998
13075    1998
13076    1998
13077    1998
13078    1998
13079    1998
13080    1998
13081    1998
13082    1998
13083    1998
13084    1998
13085    1998
13086    1998
13087    1998
13088    1998
13089    1998
Name: month, Length: 13090, dtype: int64

In [14]:
guns.loc[:4]

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274,0.0,12.0,...,0.0,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181,0.0,5.0,...,0.0,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693,0.0,18.0,...,1.0,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342,95.0,14.0,...,0.0,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019

Index(['year', 'state', 'permit', 'permit_recheck', 'handgun', 'long_gun',
       'other', 'multiple', 'admin', 'prepawn_handgun', 'prepawn_long_gun',
       'prepawn_other', 'redemption_handgun', 'redemption_long_gun',
       'redemption_other', 'returned_handgun', 'returned_long_gun',
       'returned_other', 'rentals_handgun', 'rentals_long_gun',
       'private_sale_handgun', 'private_sale_long_gun', 'private_sale_other',
       'return_to_seller_handgun', 'return_to_seller_long_gun',
       'return_to_seller_other', 'totals'],
      dtype='object')

In [36]:
guns.loc[:4]

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274,0.0,12.0,...,0.0,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181,0.0,5.0,...,0.0,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693,0.0,18.0,...,1.0,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342,95.0,14.0,...,0.0,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019

In [44]:
year_dates=[pd.to_datetime(guns['month'], yearfirst=True).dt.year]

In [51]:
guns.loc[:10]

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,returned_other,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274,0.0,12.0,...,0.0,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181,0.0,5.0,...,0.0,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693,0.0,18.0,...,1.0,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342,95.0,14.0,...,0.0,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019
5,2018-08,Colorado,10004.0,0.0,16160.0,12392.0,1062.0,971,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40922
6,2018-08,Connecticut,7057.0,466.0,4519.0,1690.0,605.0,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14338
7,2018-08,Delaware,173.0,0.0,1262.0,1162.0,85.0,58,0.0,1.0,...,0.0,0.0,0.0,67.0,27.0,2.0,0.0,0.0,0.0,2914
8,2018-08,District of Columbia,235.0,0.0,91.0,1.0,0.0,2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,329
9,2018-08,Florida,17524.0,0.0,44227.0,15734.0,3176.0,1935,7.0,92.0,...,3.0,0.0,0.0,164.0,103.0,20.0,62.0,56.0,1.0,89711
10,2018-08,Georgia,17288.0,0.0,10894.0,7419.0,431.0,486,0.0,26.0,...,0.0,0.0,0.0,28.0,21.0,4.0,0.0,0.0,0.0,40046

In [52]:
print(year_dates)

[0        2018
1        2018
2        2018
3        2018
4        2018
5        2018
6        2018
7        2018
8        2018
9        2018
10       2018
11       2018
12       2018
13       2018
14       2018
15       2018
16       2018
17       2018
18       2018
19       2018
20       2018
21       2018
22       2018
23       2018
24       2018
25       2018
26       2018
27       2018
28       2018
29       2018
         ...
13060    1998
13061    1998
13062    1998
13063    1998
13064    1998
13065    1998
13066    1998
13067    1998
13068    1998
13069    1998
13070    1998
13071    1998
13072    1998
13073    1998
13074    1998
13075    1998
13076    1998
13077    1998
13078    1998
13079    1998
13080    1998
13081    1998
13082    1998
13083    1998
13084    1998
13085    1998
13086    1998
13087    1998
13088    1998
13089    1998
Name: month, Length: 13090, dtype: int64]

In [53]:
year = {'year': year_dates}

{'year': [0        2018
1        2018
2        2018
3        2018
4        2018
5        2018
6        2018
7        2018
8        2018
9        2018
10       2018
11       2018
12       2018
13       2018
14       2018
15       2018
16       2018
17       2018
18       2018
19       2018
20       2018
21       2018
22       2018
23       2018
24       2018
25       2018
26       2018
27       2018
28       2018
29       2018
         ...
13060    1998
13061    1998
13062    1998
13063    1998
13064    1998
13065    1998
13066    1998
13067    1998
13068    1998
13069    1998
13070    1998
13071    1998
13072    1998
13073    1998
13074    1998
13075    1998
13076    1998
13077    1998
13078    1998
13079    1998
13080    1998
13081    1998
13082    1998
13083    1998
13084    1998
13085    1998
13086    1998
13087    1998
13088    1998
13089    1998
Name: month, Length: 13090, dtype: int64]}

In [55]:
guns2= guns.append(year, ignore_index=True)

In [56]:
guns2.loc[:4]

,month,state,permit,permit_recheck,handgun,long_gun,other,multiple,admin,prepawn_handgun,...,rentals_handgun,rentals_long_gun,private_sale_handgun,private_sale_long_gun,private_sale_other,return_to_seller_handgun,return_to_seller_long_gun,return_to_seller_other,totals,year
0,2018-08,Alabama,22465.0,0.0,5991.0,5741.0,218.0,274.0,0.0,12.0,...,0.0,0.0,39.0,25.0,1.0,0.0,0.0,0.0,37227.0,NaN
1,2018-08,Alaska,218.0,0.0,2593.0,3057.0,220.0,181.0,0.0,5.0,...,0.0,0.0,17.0,31.0,1.0,0.0,1.0,0.0,6818.0,NaN
2,2018-08,Arizona,12014.0,455.0,10833.0,6987.0,887.0,693.0,0.0,18.0,...,0.0,0.0,30.0,17.0,4.0,1.0,1.0,0.0,34149.0,NaN
3,2018-08,Arkansas,5684.0,690.0,4809.0,5590.0,226.0,342.0,95.0,14.0,...,0.0,0.0,20.0,13.0,6.0,0.0,0.0,0.0,20502.0,NaN
4,2018-08,California,38687.0,0.0,34617.0,25666.0,3117.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103019.0,NaN

In [1]:
# YOUR CODE HERE

pass

NameError: name 'pd' is not defined

In [19]:
assert (guns['year'].min(), guns['year'].max()) == (1998, 2018)

AssertionError:

### Part C. Subtask 2 (1 point)

Group __guns__ dataframe by year and sum up the __totals__ (together, regardless of state). Use the variables
__totals_2000__ and __totals_2017__ to store the corresponding results.

You will need https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.groupby.html

In [10]:
df =guns.groupby('month')

In [11]:
df

In [2]:
# YOUR CODE HERE
guns.groupby()
pass

NameError: name 'guns' is not defined

In [ ]:
assert totals_2000 == 8427096
assert totals_2017 == 24955919

### Part C. Subtask 3 (1 point)

Group data by state (regardless of year) and calculate the mean value of __long_gun__ and __handgun__ checks separately for each state. Calculate the number of states that had more long gun background checks on average over the years than handgun checks. Calculate the number of states with more handgun checks. Store these results in __states_with_more_long_guns__ and __states_with_more_handguns__ variables, respectively.

Hint: Use vector operations. No for loops are needed. A result of comparison of two vectors is a vector of booleans. You can sum up the vector of booleans to calculate the number of True values in it.

In [ ]:
# YOUR CODE HERE
pass

In [ ]:
assert states_with_more_long_guns == 35
assert states_with_more_handguns == 20